In [17]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [18]:
engine = create_engine(
    "sqlite:///../database/sales.db"
)

In [19]:
df = pd.read_csv(r'C:\retail-sales-dashboard\data\raw\sample_superstore.csv', encoding='cp1252')

In [42]:
df.to_sql(
    "sales_data",
    engine,
    if_exists="replace",
    index=False
)

9994

In [21]:
test_query = "SELECT * FROM sales_data LIMIT 5"

pd.read_sql(test_query, engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [52]:
query = """
SELECT sum(Sales) as total_revenue
FROM sales_Data
"""
pd.read_sql(query,engine)

   total_revenue
0   2.297201e+06

In [53]:
query= """
SELECT Category, SUM(sales) as revenue
FROM sales_data
GROUP BY Category
ORDER BY Revenue DESC
"""
pd.read_sql(query, engine)

          Category      revenue
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

In [54]:
query = """
SELECT
    Region,
    SUM(Sales) AS total_sales,
    AVG(Sales) AS avg_order_value
FROM sales_data
GROUP BY Region
ORDER BY total_sales DESC
"""
pd.read_sql(query, engine)

    Region  total_sales  avg_order_value
0     West  725457.8245       226.493233
1     East  678781.2400       238.336110
2  Central  501239.8908       215.772661
3    South  391721.9050       241.803645

In [56]:
df.columns = (
    df.columns
    .str.replace(" ", "_")
    .str.replace("-", "_")
)


query = """
SELECT
    Customer_Name,
    SUM(Sales) AS customer_revenue
FROM sales_data
GROUP BY Customer_Name
ORDER BY customer_revenue DESC
LIMIT 10
"""
pd.read_sql(query, engine)

        Customer_Name  customer_revenue
0         Sean Miller         25043.050
1        Tamara Chand         19052.218
2        Raymond Buch         15117.339
3        Tom Ashbrook         14595.620
4       Adrian Barton         14473.571
5        Ken Lonsdale         14175.229
6        Sanjit Chand         14142.334
7        Hunter Lopez         12873.298
8        Sanjit Engle         12209.438
9  Christopher Conant         12129.072

In [58]:
query = """
SELECT
    -- Assumes date is like 'YYYY-MM-DD'.
    SUBSTR(Order_Date, 1, 7) AS month, 
    SUM(Sales) AS monthly_revenue
FROM sales_data
GROUP BY month
ORDER BY month
"""
monthly_sql = pd.read_sql(query, engine)

monthly_sql.head()

     month  monthly_revenue
0  1/1/201         1481.828
1  1/10/20         1247.684
2  1/11/20          159.384
3  1/12/20         1703.134
4  1/13/20         8795.403